- alias: Включить тестовую лампу по датчику движения
  trigger:
    platform: state
    entity_id: binary_sensor.pir_motion
    to: 'on'

  action:
    service: light.turn_on
    entity_id: light.sonoff_mini_1000b61314
    
    
- alias: Выключить тестовую лампу после движения
  trigger:
    platform: state
    entity_id: binary_sensor.pir_motion
    to: 'off'
    for:
      seconds: 10
  action:
    service: light.turn_off
    entity_id: light.sonoff_mini_1000b61314